language: node_js
node_js:
  - 14

jobs:
  include:
    - language: node_js
      node_js: '14'
      warnings_are_errors: false
      
      cache:
        directories:
          - node_modules

      install:
        - npm install
        
      script:
        - npm run test
        - npm run build

      deploy:
        - provider: firebase
          script: ./travis_merge_script.sh
          skip_cleanup: true
          token: $FIRE_TOKEN
          on:
            branch: dev

        - provider: firebase
          skip_cleanup: true
          token: $FIRE_TOKEN
          on:
            branch: master
        