language: node_js
node_js:
  - 14

jobs:
  include:
    - language: node_js
      node_js: '14'
      warnings_are_errors: false
      
      cache:
        directories:
          - node_modules

      install:
        - npm install
        
      script:
        - npm run build
        - npm run test

      deploy:
        - provider: firebase
          skip_cleanup: true
          token: $FIRE_TOKEN
          on:
            branch: master
        