language: node_js
node_js:
  - 14

jobs:
  include:
    - language: node_js
      node_js: '14'
      warnings_are_errors: false
      
      cache:
        directories:
          - node_modules

      branches:
        only:
          - master

      install:
        - npm install
        
      script:
        - npm run test

      deploy:
        provider: firebase
        skip_cleanup: true
        token: $FIREBASE_TOKEN
      
      after_success:
        - ./travis_merge_script.sh
